2016-05-09 10:24:47,891 - MainProcess - processing - DEBUG - 48 - Processing file for PinutUser:PinutUser_b827eb9fde83_24_04_2016.json
2016-05-09 10:24:47,897 - MainProcess - processing - DEBUG - 146 - ****************************************************************
2016-05-09 10:24:47,903 - MainProcess - processing - DEBUG - 148 - Processing of file successful ... Moving it to Processedjson folder
2016-05-09 10:24:47,903 - MainProcess - processing - DEBUG - 218 - user_dict: {'ola': [{(1, '24-04-2016', 'b8:27:eb:9f:de:83', '10:A5:D0:16:86:B2'): {'movie_list': [u'(500) Days of Summer.mp4', u'A Lot Like Love.avi', u'12 Angry Men.mp4'], 'email_id': u'nhgyuu@/^^?', 'device_timestamp': 1461490899, 'phone': 987, 'content_version': '1', 'viewership': {'12 Angry Men.mp4': 0, 'A Lot Like Love.avi': 2, '(500) Days of Summer.mp4': 2}, 'connection_count': 8, 'music_list': [], 'others_list': []}}]}
2016-05-09 10:41:36,348 - MainProcess - processing - ERROR - 220 - Exception[name 'sys' is not defined]
Traceback (most recent call last):
  File "analytics/processing.py", line 215, in <module>
    sys.exit(0)
NameError: name 'sys' is not defined
